#!/bin/bash
# This script will download cross sections in ACE or H5 format
     
# set -e    # x

WORK_DIR=$1                                 # Where to put data/XS
XS_H5_Library=$2
XS_ACE_Library=$3
DEPLETION_CHAIN_DATA=$4
XS_Library=$5
ENVNAME=$6
#===============================================================================
DATA_DIR=$WORK_DIR/data

function recent_file(){
    unset -v latest
    patern=$1
    for file in $patern*?
        do
            [[ $file -nt $latest ]] && latest=$file
        done
    return
}

if [[ ! -d "$DATA_DIR" ]]; then
    mkdir $DATA_DIR
fi
cd $DATA_DIR
pwd
#===============================================================================
#                       Download official HDF5 data  
# The data libraries listed here have been produced by the OpenMC development
# team and are as complete as possible
#===============================================================================
# Download NNDC distribution
if [[ $XS_H5_Library == NNDC ]]; then 
    H5=$DATA_DIR/nndc_hdf5       
    if [[ ! -e $H5/cross_sections.xml ]]; then
        time wget -c https://anl.box.com/shared/static/teaup95cqv8s9nn56hfn7ku8mmelr95p.xz 
        recent_file "teau"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
    else 
        echo "=================        " $H5"  data already exist !            ================"
    fi
    exit
fi
# Download ENDF-B/VIII.0 distribution : This library includes incident neutron, photoatomic, 
# atomic relaxation, and thermal scattering data from ENDF/B-VIII.0. All ACE files were produced 
# using NJOY 2016.59. Incident neutron data is available at six temperatures: 250 K, 293.6 K, 600 K, 
# 900 K, 1200 K, and 2500 K.
if [[ $XS_H5_Library == ENDF-B/VIII.0 ]]; then        
    H5=$DATA_DIR/endfb80_hdf5
    if [[ ! -e $H5/cross_sections.xml ]]; then
        time wget -c https://anl.box.com/shared/static/uhbxlrx7hvxqw27psymfbhi7bx7s6u6a.xz
        recent_file "uhbx"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
    else 
        echo "=================      " $H5 "  data already exist !       ================"
    fi
    exit
fi
# Download ENDF-B/VII.1 distribution
# This library includes incident neutron, photoatomic, thermal scattering,  
# and windowed multipole data. All ACE files were produced using NJOY 2016.44. 
# Incident neutron data is available at six temperatures: 250 K, 293.6 K, 600 K, 900 K, 1200 K, and 2500 K. 
# Note that elastic scattering cross sections are also available at 0 K
if [[ $XS_H5_Library == ENDF-B/VII.1 ]]; then        
    H5=$DATA_DIR/endfb71_hdf5
    if [[ ! -e $H5/cross_sections.xml ]]; then
        time wget -c https://anl.box.com/shared/static/9igk353zpy8fn9ttvtrqgzvw1vtejoz6.xz
        recent_file "9igk"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
    else 
        echo "=================      " $H5 " data already exist !       ================"
    fi
    exit
fi
# Download JEFF3.3 distribution ; This library includes incident neutron and thermal scattering 
# data from JEFF 3.3. All ACE files were produced using NJOY 2016.59. The photoatomic and atomic 
# relaxation data from ENDF/B-VIII.0 has also been included because JEFF 3.3 does not release its 
# own photoatomic or atomic relaxation sublibraries. Incident neutron data is available at six 
# temperatures: 250 K, 293.6 K, 600 K, 900 K, 1200 K, and 2500 K. 
# Note that the C13 and O17 cannot be processed by NJOY 2016.59 due to a bug in the evaluations. 
# These nuclides have been replaced by data from TENDL-2019 (the original evaluations from JEFF 3.3 
# were taken from TENDL-2015)
if [[ $XS_H5_Library == JEFF-3.3 ]]; then        
    H5=$DATA_DIR/jeff33_hdf5
    if [[ ! -e $H5/cross_sections.xml ]]; then
        time wget -c https://anl.box.com/shared/static/4jwkvrr9pxlruuihcrgti75zde6g7bum.xz
        recent_file "4jwk"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
    else 
        echo "=================        " $H5 " data already exist !        ================"
    fi
    exit
fi
#===============================================================================
#              Downloaded MCNP ACE files converted to H5 format
#===============================================================================

# Download MCNP ENDF-B/VIII.0 distribution : This library was produced by converting 
# ACE files from the Lib80x and ENDF80SaB2 libraries that were generated by the Nuclear 
# Data Team at LANL. Incident neutron data is available at seven temperatures: 
# 0.1 K, 250 K, 293.6 K, 600 K, 900 K, 1200 K, and 2500 K.
if [[ $XS_H5_Library == MCNP_ENDF-B/VIII.0 ]]; then        
    H5=$DATA_DIR/lib80x_hdf5
    if [[ ! -e $H5/cross_sections.xml ]]; then
        time wget -c https://anl.box.com/shared/static/nd7p4jherolkx4b1rfaw5uqp58nxtstr.xz
        recent_file "nd7p"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
    else 
        echo "=================     " $latest " data already exist !       ================"
    fi
    exit
fi
# Download MCNP ENDF-B/VII.1 distribution : This library was produced by converting ACE files from the 
# endf71x and ENDF71SaB libraries that were generated by the Nuclear Data Team at LANL and distributed 
# with MCPN5/6. Incident neutron data is available at seven temperatures: 0.1 K, 250 K, 293.6 K, 600 K, 
# 900 K, 1200 K, and 2500 K. Incident photon data converted from the eprdata14 library is also included.
if [[ $XS_H5_Library == MCNP_ENDF-B/VII.1 ]]; then        
    H5=$DATA_DIR/mcnp_endfb71
    if [[ ! -e $H5/cross_sections.xml ]]; then
        time wget -c https://anl.box.com/shared/static/d359skd2w6wrm86om2997a1bxgigc8pu.xz
        recent_file "d359"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
    else
        echo "=================         " $H5 " data already exist !       ================"
    fi
    exit
fi
# Download MCNP ENDF-B/VII.0 distribution : This library was produced by converting ACE files generated 
# by the Nuclear Data Team at LANL and distributed with MCNP5/6. Incident neutron data was converted 
# from endf70[a-k] files, thermal scattering data from endf70sab, and incident photon data from the 
# eprdata14 library. Incident neutron data is available at five temperatures: 293.6 K, 600 K, 900 K, 
# 1200 K, and 2500 K
if [[ $XS_H5_Library == MCNP_ENDF-B/VII.0 ]]; then        
    H5=$DATA_DIR/mcnp_endfb70
    if [[ ! -e $H5/cross_sections.xml ]]; then        
        time wget -c https://anl.box.com/shared/static/t25g7g6v0emygu50lr2ych1cf6o7454b.xz
        recent_file "t25g"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
    else 
        echo "=================         " $H5 " data already exist !        ================"
    fi
    exit
fi
# Download JEFF-3.3 distribution : This library was produced by converting ACE files generated by NEA. 
# It includes incident neutron data as well as thermal scattering data for 21 different compounds. 
# Incident neutron data is available at 6 temperatures: 293.6 K, 600 K, 900 K, 1200 K, 1500 K, and 1800 K.
if [[ $XS_H5_Library == ACE2H5_JEFF-3.3 ]]; then        
    H5=$DATA_DIR/jeff-3.3-hdf5
    if [[ ! -e $H5/cross_sections.xml ]]; then        
        time wget -c https://anl.box.com/shared/static/ddetxzp0gv1buk1ev67b8ynik7f268hw.xz
        recent_file "ddet"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
    else 
        echo "=================        " $H5 " data already exist !        ================"
    fi
    exit
fi
# Download JEFF-3.2 distribution : This library was produced by converting ACE files generated by NEA. 
# It includes incident neutron data as well as thermal scattering data for 21 different compounds. 
# Incident neutron data is available at 6 temperatures: 293.6 K, 600 K, 900 K, 1200 K, 1500 K, and 1800 K.
if [[ $XS_H5_Library == ACE2H5_JEFF-3.2 ]]; then        
    H5=$DATA_DIR/jeff32_hdf5
    if [[ ! -e $H5/cross_sections.xml ]]; then        
        time wget -c https://anl.box.com/shared/static/pb94oxriiipezysu7w4r2qdoufc2epxv.xz
        recent_file "pb94"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
    else 
        echo "=================        " $H5 " data already exist !          ================"
    fi
    exit
fi

#===============================================================================
#                           Download ACE data
#===============================================================================
if grep -q "ACE" <<< "$XS_ACE_Library"; then     
     if [ "$(which curl)" == "" ]; then
    	conda install curl
     fi
fi    
if [[ $XS_ACE_Library == ACE-ENDF-B/VII.1_293K ]]; then        
    # This page presents the ACE formatted files for the 423 materials in the 
    # ENDF/B-VII.1 neutron reaction sublibrary and the 20 materials in the 
    # ENDF/B-VII.1 thermal neutron scattering sublibrary.   These files were # 
    # generated by the NNDC using the processing code NJOY99.368 (except for Cl-35 
    # which was generated using NJOY2010)  T=293.6K
    ENDF=$DATA_DIR/ENDF-B-VII.1-neutron-293.6K
    H5=$DATA_DIR/endfb71_ace2H5-293.6K
    echo "================    downloading   ENDF-B-VII.1-neutron-293.6K.tar.gz      ================"
    time curl --output ENDF-B-VII.1-neutron-293.6K.tar.gz https://www.nndc.bnl.gov/endf/b7.1/aceFiles/ENDF-B-VII.1-neutron-293.6K.tar.gz
    recent_file "ENDF-B-VII.1-neutron-293"
    echo "================    will expand file " $latest "      ================"
    tar -xvf $latest
    echo "================    downloading   ENDF-B-VII.1-tsl.tar.gz     ================"
    time curl --output ENDF-B-VII.1-tsl.tar.gz https://www.nndc.bnl.gov/endf/b7.1/aceFiles/ENDF-B-VII.1-tsl.tar.gz
    recent_file "ENDF-B-VII.1-tsl"
    echo "================    will expand file " $latest "      ================"
    tar -xvf ../$latest
    echo directory >$ENDF/xsdir0
    cat $ENDF/xsdir >>$ENDF/xsdir0
    cat $ENDF/xsdir >>/$ENDF/xsdir0
fi
if [[ $XS_ACE_Library == ACE-ENDF-B/VII.1_300K ]]; then        
    # This page presents the ACE formatted files for the 423 materials in the 
    # ENDF/B-VII.1 neutron reaction sublibrary and the 20 materials in the 
    # ENDF/B-VII.1 thermal neutron scattering sublibrary.   These files were # 
    # generated by the NNDC using the processing code NJOY99.368 (except for Cl-35 
    # which was generated using NJOY2010)  T=300K
    ENDF=$DATA_DIR/ENDF-B-VII.1-neutron-300K
    H5=$DATA_DIR/endfb71_ace2H5-300K
    echo "================    downloading   ENDF-B-VII.1-neutron-300K.tar.gz      ================"
    time curl --output ENDF-B-VII.1-neutron-300K.tar.gz https://www.nndc.bnl.gov/endf/b7.1/aceFiles/ENDF-B-VII.1-neutron-300K.tar.gz
    recent_file "ENDF-B-VII.1-neutron-300K"
    echo "================    will expand file " $latest "      ================"
    tar -xvf $latest
    echo "================    downloading   ENDF-B-VII.1-tsl.tar.gz      ================"
    time curl --output ENDF-B-VII.1-tsl.tar.gz https://www.nndc.bnl.gov/endf/b7.1/aceFiles/ENDF-B-VII.1-tsl.tar.gz
    recent_file "ENDF-B-VII.1-tsl"
    echo "================    will expand file " $latest "      ================"
    tar -xvf $latest
    echo directory >$ENDF/xsdir0
    cat $ENDF/xsdir >>$ENDF/xsdir0
    cat $ENDF/xsdir >>/$ENDF/xsdir0
fi
if [[ $XS_ACE_Library == ACE-ENDF-B/VIII.0 ]]; then        
    # ENDF/B-VIII.0
    # This library is based on ENDF/B-VIII.0. It contains ACE files for 
    # continuous-energy incident neutrons. These have been processed to the 
    # following temperatures (with the respective ZAID extensions).
    ENDF=$DATA_DIR/Lib80x/
    echo "================    downloading   Lib80x.tgz      ================"
    time curl --output Lib80x.tgz https://nucleardata.lanl.gov/ACE/Production/Lib80x.tgz
    recent_file "Lib80x"
    echo "================    will expand file " $latest "      ================"
    tar -zxvf $latest
    H5=$DATA_DIR/endfb80_ace2H5
    # S(a,b)  ENDF/B-VIII.0
    # The thermal scattering library based on ENDF/B-VIII.0 contains 34 materials. 
    # The material identifiers (for use on the MTn card in MCNP) are given in the 
    # table below. For those that have a room temperature evaluation, that data 
    # table has extension 40t. The full documentation for the ENDF80SaB library can 
    # be found in the docs directory after decompressing the download.
    echo "================    downloading  ENDF80SaB2.tgz      ================"
    time curl --output ENDF80SaB2.tgz https://nucleardata.lanl.gov/ACE/Production/ENDF80SaB2.tgz
    recent_file "ENDF80SaB2"
    echo "================    will expand file " $latest "      ================"
    tar -zxvf $latest
    mv ENDF80SaB2/ENDF80SaB2 $ENDF/.
    echo directory >$ENDF/xsdir0
    cat $ENDF/xsdir >>$ENDF/xsdir0
    cat ENDF80SaB2/xsdir >>/$ENDF/xsdir0
fi

if grep -q "ACE-JEFF-3.3" <<< "$XS_ACE_Library"; then 
    # JEFF-3.3 is a thorough update of the neutron, decay data, fission yields, dpa and neutron 
    # activation libraries in the EAF format, with neutron thermal scattering files for 20 compounds. 
    # Special sub-libraries for incident alphas, deuterons, gammas, helium-3, protons and tritons have 
    # been contributed by the TENDL-2017 library and adopted as part of the JEFF-3.3 release. JEFF-3.3 
    # was officially released on November 20, 2017. Temperatures : 293, 600, 900, 1200, 1500 and 1800K 
    # URL = https://www.oecd-nea.org/dbdata/jeff/jeff33/index.html
    ENDF=$DATA_DIR/JEFF3.3_ACE
    H5=$DATA_DIR/JEFF3.3_ace2H5
    mkdir $ENDF
    # JEFF-3.3 xsdir file
    echo "================    downloading   xsdir.jeff33      ================"
    curl --output xsdir.jeff33 https://www.oecd-nea.org/dbdata/jeff/jeff33/downloads/temperatures/xsdir.jeff33

    if [[ $XS_ACE_Library == ACE-JEFF-3.3_293K ]]; then
        echo "================    downloading  ace_293.tar.gz      ================"
        time curl --output ace_293.tar.gz https://www.oecd-nea.org/dbdata/jeff/jeff33/downloads/temperatures/ace_293.tar.gz
        recent_file "ace_293"
        pattern="293.ace"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
        mv ace_293/* $ENDF/.
    fi

    if [[ $XS_ACE_Library == ACE-JEFF-3.3_600K ]]; then
        echo "================    downloading  ace_600.tar.gz      ================"
        time curl --output ace_600.tar.gz https://www.oecd-nea.org/dbdata/jeff/jeff33/downloads/temperatures/ace_600.tar.gz
        recent_file "ace_600"
        pattern="600.ace"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
        mv ace_600/* $ENDF/.
    fi
        
    if [[ $XS_ACE_Library == ACE-JEFF-3.3_900K ]]; then
        echo "================    downloading  ace_900.tar.gz      ================"
        time curl --output ace_900.tar.gz https://www.oecd-nea.org/dbdata/jeff/jeff33/downloads/temperatures/ace_900.tar.gz
        recent_file "ace_900"
        pattern="900.ace"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
        mv ace_900/* $ENDF/.
    fi

    if [[ $XS_ACE_Library == ACE-JEFF-3.3_1200K ]]; then
        echo "================    downloading  ace_1200.tar.gz      ================"
        time curl --output ace_1200.tar.gz https://www.oecd-nea.org/dbdata/jeff/jeff33/downloads/temperatures/ace_1200.tar.gz
        recent_file "ace_1200"
        pattern="1200.ace"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
        mv ace_1200/* $ENDF/.
    fi

    if [[ $XS_ACE_Library == ACE-JEFF-3.3_1500K ]]; then
        echo "================    downloading  ace_1500.tar.gz      ================"
        time curl --output ace_1500.tar.gz https://www.oecd-nea.org/dbdata/jeff/jeff33/downloads/temperatures/ace_1500.tar.gz
        recent_file "ace_1500"
        pattern="1500.ace"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
        mv ace_1500/* $ENDF/.
    fi

    if [[ $XS_ACE_Library == ACE-JEFF-3.3_1800K ]]; then
        echo "================    downloading  ace_1800.tar.gz      ================"
        time curl --output ace_1800.tar.gz https://www.oecd-nea.org/dbdata/jeff/jeff33/downloads/temperatures/ace_1800.tar.gz
        recent_file "ace_1800"
        pattern="1800.ace"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
        mv ace_1800/* $ENDF/.
    fi

    if [[ $XS_ACE_Library == ACE-JEFF-3.3_TSL ]]; then
        echo "================    downloading  S(a,b) " $latest " file     ================"
        time curl --output ace_tsl.tar.gz https://www.oecd-nea.org/dbdata/jeff/jeff33/downloads/temperatures/ace_tsl.tar.gz
        recent_file "ace_tsl"
        echo "================    will expand file " $latest "      ================"
        tar -zxvf $latest
        mv ace_tsl/* $ENDF/.
        if [[ ! -e $ENDF/xsdir0 ]]; then
            echo directory >$ENDF/xsdir0
        fi
        grep '\<..t\>' xsdir.jeff33 >>/$ENDF/xsdir0
    fi
    if [[ $XS_ACE_Library != ACE-JEFF-3.3_TSL ]]; then
        if [[ ! -e $ENDF/xsdir0 ]]; then
            echo directory >$ENDF/xsdir0
        fi
        echo "$(grep -v '\<..t\>' xsdir.jeff33)" |grep $pattern >>$ENDF/xsdir0
    fi
fi

if [[ $XS_ACE_Library != none ]]; then   
    conda activate $ENVNAME
    if [[ ! -e $H5/cross_sections.xml ]]; then
        if [[ ! -d "$H5" ]]; then
            mkdir $H5 && cd $H5
        else
            cd $H5
        fi
        openmc-ace-to-hdf5 --xsdir $ENDF/xsdir0
    else
        echo "============ " $H5 " data already exist and new ones will be merged to ! ============"
        tmp=temp
        if [[ ! -d "$tmp" ]]; then
            mkdir $tmp && cd $tmp
        else
            cd $tmp
        fi
        openmc-ace-to-hdf5 --xsdir $ENDF/xsdir0
        mv *.h5 $H5
        cat cross_sections.xml >>$H5/cross_sections.xml
        cd .. && rm -rf $tmp
    fi
fi
#===============================================================================
# Depletion data
#===============================================================================
if [[ $DEPLETION_CHAIN_DATA != none ]]; then 
    if [[ ! -d "$DATA_DIR/depletion_chain" ]]; then 
        mkdir -p $DATA_DIR/depletion_chain && cd $DATA_DIR/depletion_chain
    else
        cd $DATA_DIR/depletion_chain
    fi
fi
# ----------------------ENDF-BVII.1 PWR spectrum------------------------------
if [[ $DEPLETION_CHAIN_DATA == ENDF-BVII.1_PWR_spectrum_v0.11 ]]; then        
    # ENDF/B-VII.1 PWR spectrum readable by openmc version 0.11 only
    wget https://anl.box.com/shared/static/1ndcrc1j042nkdpfobp5ebsyxghziisc.xml
    mv 1ndcrc1j042nkdpfobp5ebsyxghziisc.xml pwr_spectrum_B71_chain_v011.xml
    exit
fi
if [[ $DEPLETION_CHAIN_DATA == ENDF-BVII.1_PWR_spectrum_v0.12 ]]; then        
    # ENDF/B-VII.1 PWR spectrum data readable by openmc version 0.12 only
    wget https://anl.box.com/shared/static/os1u896bwsbopurpgas72bi6aij2zzdc.xml
    mv os1u896bwsbopurpgas72bi6aij2zzdc.xml pwr_spectrum_B71_chain_v012.xml
    exit
fi
# ----------------------ENDF-BVII.1 fast spectrum-----------------------------
if [[ $DEPLETION_CHAIN_DATA == ENDF-BVII.1_fast_spectrum_v0.11 ]]; then        
    # Fast spectrum data readable by openmc version 0.11 only
    wget https://anl.box.com/shared/static/bb7sfrrf6pyyoa5zoa2sxiuy7mvn5kza.xml
    mv bb7sfrrf6pyyoa5zoa2sxiuy7mvn5kza.xml fast_spectrum_B71_chain_v011.xml
    exit
fi
if [[ $DEPLETION_CHAIN_DATA == ENDF-BVII.1_fast_spectrum_v0.12 ]]; then        
    # Fast spectrum data readable by openmc version 0.12 only
    wget https://anl.box.com/shared/static/9058zje1gm0ekd93hja542su50pccvj0.xml
    mv 9058zje1gm0ekd93hja542su50pccvj0.xml fast_spectrum_B71_chain_v012.xml
    exit
fi
# ----------------------Simplified chain PWR spectrum-----------------------------
if [[ $DEPLETION_CHAIN_DATA == Simplified_chain_PWR_spectrum_v0.11 ]]; then        
    # PWR spectrum simplified data readable by openmc version 0.11 only
    wget https://anl.box.com/shared/static/lv4b1epe8kwfvqtzhaik19outb9s4vta.xml
    mv lv4b1epe8kwfvqtzhaik19outb9s4vta.xml pwr_spectrum_simple_chain_v011.xml
    exit
fi
if [[ $DEPLETION_CHAIN_DATA == Simplified_chain_PWR_spectrum_v0.12 ]]; then        
    # PWR spectrum simplified data readable by openmc version 0.12 only
    wget https://anl.box.com/shared/static/3nvnasacm2b56716oh5hyndxdyauh5gs.xml
    mv 3nvnasacm2b56716oh5hyndxdyauh5gs.xml pwr_spectrum_simple_chain_v012.xml
    exit
fi
# ----------------------Simplified chain fast spectrum-----------------------------
if [[ $DEPLETION_CHAIN_DATA == Simplified_chain_fast_spectrum_v0.11 ]]; then        
    # Fast spectrum data readable by openmc version 0.11 only
    wget https://anl.box.com/shared/static/4j27ca0l112krbw9nldj195bqik9qgvn.xml
    mv 4j27ca0l112krbw9nldj195bqik9qgvn.xml fast_spectrum_simple_chain_v011.xml
    exit
fi
if [[ $DEPLETION_CHAIN_DATA == Simplified_chain_fast_spectrum_v0.12 ]]; then        
    # Fast spectrum data readable by openmc version 0.12 only
    wget https://anl.box.com/shared/static/9fqbq87j0tx4m6vfl06pl4ccc0hwamg9.xml
    mv 9fqbq87j0tx4m6vfl06pl4ccc0hwamg9.xml fast_spectrum_simple_chain_v012.xml
    exit
fi

#===============================================================================
# Download ENDF/B-VII.1 distribution evaluation : ENDF format file
if [[ $XS_Library == ENDF-B/VII.1 ]]; then        
    ENDF=$DATA_DIR/endf-b-vii.1
    if [ "$(which curl)" == "" ]; then
    	conda install curl
    fi
    if [[ ! -d $ENDF/neutrons || ! -d $ENDF/photoat || ! -d $ENDF/atomic_relax ]]; then
        time curl --output 4kd2gxnf4gtk4w1c8eua5fsua22kvgjb.xz https://anl.box.com/shared/static/4kd2gxnf4gtk4w1c8eua5fsua22kvgjb.xz
        recent_file "ace_tsl"
        echo "================    will expand file " $latest "      ================"
        tar -xvf $latest
    else 
        echo "=================       $latest data already exist !          ================"
    fi
    exit
fi    
if [[ $XS_Library == JENDL-4.0 ]]; then        
    ENDF=$DATA_DIR/jendl40
    if [ "$(which curl)" == "" ]; then
    	conda install curl
    fi
    if [[ ! -d $ENDF/neutrons || ! -d $ENDF/photoat || ! -d $ENDF/atomic_relax ]]; then
        time curl --output jendl40-or-up_20160106.tar.gz https://wwwndc.jaea.go.jp/ftpnd/ftp/JENDL/jendl40-or-up_20160106.tar.gz
        tar -zxvf jendl40-or-up_20160106.tar.gz
    else 
        echo "=================       $latest data already exist !          ================"
    fi
    curl --output jendl40-sct.tar https://wwwndc.jaea.go.jp/ftpnd/ftp/JENDL/jendl40-sct.tar
    tar xvf jendl40-sct.tar
    exit
fi
